classes_dict = {'riaziat_mohandesi_1' : {'Day': 'Sunday', 'Time_Hour': 13, 'Time_Minute': 30},
                'riaziat_mohandesi_2' : {'Day': 'Sunday', 'Time_Hour': 15, 'Time_Minute': 15},
                'system_amel_1' : {'Day': 'Thursday', 'Time_Hour': 7, 'Time_Minute': 30},
                'system_amel_2' : {'Day': 'Thursday', 'Time_Hour': 9, 'Time_Minute': 15},
                'ravesh_pajohesh' : {'Day': 'Sunday', 'Time_Hour': 17, 'Time_Minute': 0},
                'memary_computer_1' : {'Day': 'Thursday', 'Time_Hour': 13, 'Time_Minute': 30},
                'memary_computer_2' : {'Day': 'Thursday', 'Time_Hour': 15, 'Time_Minute': 15},
                'sakhteman_dade_1' : {'Day': 'Saturday', 'Time_Hour': 13, 'Time_Minute': 30},
                'sakhteman_dade_2' : {'Day': 'Saturday', 'Time_Hour': 15, 'Time_Minute': 15},
                'amar_ehtemal_mohandesy_1' : {'Day': 'Monday', 'Time_Hour': 9, 'Time_Minute': 15},
                'amar_ehtemal_mohandesy_2' : {'Day': 'Monday', 'Time_Hour': 11, 'Time_Minute': 0},
                'tarikh_farhang' : {'Day': 'Sunday', 'Time_Hour': 15, 'Time_Minute': 15},
                'varzesh' : {'Day': 'Sunday', 'Time_Hour': 9, 'Time_Minute': 15},
}